"""
The AI class represents the AI opponent in the game.
It's responsible for generating its own game board and placing its ships randomly.

The AI will make decisions on where to guess based on the information provided in the sentences and its strategies.

"""
from .constants import *
from .ship import *

class AI:
    """
    Represents a ship object in the game.
    """

    # Define a class-level variable to hold the AI modes
    POSSIBLE_MODES = ["Target", "Hunt"]

    def __init__ (self, board):
        """
        Constructor for the Ship class.
        """

        self.board = board
        self.ships = []
        self.moves_made = set()
        self.mode = AI.POSSIBLE_MODES[0]


    def generate_coords(self, length):
        """
        Generates a random set of coordinates, ensuring they are consecutive and do not contain a ship.
        """

        while True:
            # Determine the direction (horizontal or vertical) randomly.
            orientation = random.choice(['vertical', 'horizontal'])

            # Randomly select the starting position.
            if orientation == 'horizontal':
                start_row = random.randint(0, 9 - 1)
                start_col = random.randint(0, 9 - length)
            else:
                start_row = random.randint(0, 9 - length)
                start_col = random.randint(0, 9 - 1)

            # Generate consecutive coordinates based on the chosen direction.
            coords = []
            for i in range(length):
                if orientation == 'horizontal':
                    coords.append((start_row, start_col + i))
                else:
                    coords.append((start_row + i, start_col))

            # Check if the generated coordinates contain any cells with ships.
            has_ship = any(self.board[row][col].ship for row, col in coords)

            # If there are no ships in the generated coordinates, return them.
            if not has_ship:
                return coords


    def place_ship(self, win, length):
        """
        Places AI ship on the game board using coordinates generated by generate_coords.
        """

        coords = self.generate_coords(length)

        temp_cells = []
        for (row, col) in coords:
            temp_cells.append(self.board.get_cell(row, col))

        ship = Ship(temp_cells)  # Creates the ship
        self.board.draw_ship(win, ship)
        self.ships.append(ship)  # Stores all the AI ships
        self.board.update_board()
        
        return ship


